### ISSUE TITLE
develop CI: Python SDK Tests red on sentence-transformers (ImportError + _FakeSentenceTransformer.encode convert_to_tensor)

### ISSUE THREAD

**Issue by vjsingh1984** [vjsingh1984/proximaDB#73]
**Heads-up for the Python SDK / embedding work** — `develop`'s **Python SDK Tests** leg (3.10/3.11/3.12) is red on `sentence_transformers`-related failures, unrelated to the API v2 consolidation (PR #68) or the URL-validator fix (PR #71, just merged — `test_url_grpc_hostport_kept_asis` is resolved).

### Failing tests (from PR #71 CI run `27788052106`, job `82235951587`)
```
FAILED tests/unit/test_embedding_providers_v2.py::TestGTEQwenProvider::test_embed_query    - ImportError: cannot import name 'SentenceTransformer' from 'sentence_transformers' (unknown location)
FAILED tests/unit/test_embedding_providers_v2.py::TestGTEQwenProvider::test_embed_passages - (same ImportError)
FAILED tests/unit/test_embedding_providers_v2.py::TestGTEQwenProvider::test_embed_batch    - (same)
FAILED tests/unit/test_embedding_providers_v2.py::TestGTEQwenProvider::test_model_caching  - (same)
FAILED tests/unit/test_embedding_providers_v2.py::TestGTEQwenProvider::test_context_manager- (same)
FAILED tests/unit/test_atomic_wal.py::test_atomic_wal_behavior                              - TypeError: _FakeSentenceTransformer.encode() got an unexpected keyword argument 'convert_to_tensor'
FAILED tests/unit/test_quantization_features.py::TestQuantizationIntegration::test_search_with_optimization_hints - (same TypeError)
```

### Two distinct causes
1. **`ImportError: cannot import name 'SentenceTransformer' from 'sentence_transformers' (unknown location)`** — the CI env's `sentence-transformers` is broken/shadowed (note "unknown location" — likely a namespace/stub package collision or a missing/partial install).
2. **`_FakeSentenceTransformer.encode() got an unexpected keyword argument 'convert_to_tensor'`** — a test fake's `encode()` signature has drifted from the calling code, which now passes `convert_to_tensor=`.

Most likely introduced by the recent embedding/multimodal-consolidation + arrow58/datafusion54 dependency work on develop. This blocks the Python SDK leg from going green even though the config-test fix is in. Could whoever owns the embedding refactor take a look? (The fix is almost certainly: update `_FakeSentenceTransformer.encode(**kwargs)` to accept/ignore `convert_to_tensor`, and ensure `sentence-transformers` resolves in the SDK test env.)
